accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name='accounts'
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('products/', views.products, name='products'),
    path('all_orders/', views.all_orders, name='all_orders'),
    path('customer/<int:pk>/', views.customer, name='customer'),

    path('create_order/<int:pk>/', views.create_order, name='create_order'),
    path('update_order/<int:pk>/', views.update_order, name='update_order'),
    path('delete_order/<int:pk>/', views.delete_order, name='delete_order'),

    path('logoutUser/', views.logoutUser, name='logoutUser'),
    path('loginPage/', views.loginPage, name='loginPage'),
    path('register/', views.register, name='register'),
    path('user/', views.userPage, name='userPage'),

    path('create-purchase/', views.create_purchase, name='create_purchase'),


    path('user/', views.userPage, name='userPage'),

    # Password Reset

]

'''
1 - Submit email form                         //PasswordResetView.as_view()
2 - Email sent success message                //PasswordResetDoneView.as_view()
3 - Link to password Rest form in email       //PasswordResetConfirmView.as_view()
4 - Password successfully changed message     //PasswordResetCompleteView.as_view()
'''

product/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # This is accounts url
    path('', include('accounts.urls')),

    path('admin/', admin.site.urls),


    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='accounts/password_reset.html'),name='password_reset'),

    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html'),name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_confirm.html'),name='password_reset_confirm'),

    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True)
    email = models.EmailField(null=True)
    profile_pic = models.ImageField(default='default.jpeg', null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    Cat = (
        ('Stone', 'Stone'),
        ('Soil', 'Soil'),
        ('Sand', 'Sand'),
        )
    name = models.CharField(max_length=200, null=True)
    price = models.FloatField(null=True)
    category = models.CharField(max_length=200, choices=Cat, null=True)
    description = models.TextField(null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.name

class Order(models.Model):
    STATUS = (
            ('Pending', 'Pending'),
            ('Out for delivery', 'Out for delivery'),
            ('Delivered', 'Delivered'),
        )

    customer = models.ForeignKey(Customer, null=True, on_delete=models.SET_NULL)
    product = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    status = models.CharField(max_length=200, null=True, choices=STATUS)
    note = models.CharField(max_length=1000, null=True)

    def __str__(self):
        return self.product.name



# Create your models here.
class Purchase(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    brand = models.CharField(max_length=20, blank=True)
    cost_price = models.IntegerField(default=0)
    selling_price = models.IntegerField(default=0)
    qty = models.IntegerField(default=0)
    discount = models.IntegerField(default=0)
    is_discount_in_parcentage = models.BooleanField(default=False, verbose_name='Discount %')
    created = models.DateTimeField(auto_now_add=True)
    purchase_by = models.CharField(max_length=20)

    def __str__(self):
        return str(self.id)

accounts/forms.py
from django.forms import ModelForm
from . models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from accounts.models import Purchase
class CreateOrderForm(ModelForm):
    class Meta:
        model = Order
        fields = '__all__'

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'
        exclude = ['user']
        

class ModelPurchaseForm(forms.ModelForm):
    class Meta:
        model = Purchase
        fields = '__all__'

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . models import Product, Order, Customer
from . forms import *
from django.forms import inlineformset_factory
from . filters import OrderFilter
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from . decorators import unauthenticated_user, allowed_users, admin_only
from django.contrib.auth.models import Group


# Create your views here.
@login_required(login_url='accounts:loginPage')
@admin_only
def dashboard(request):
    customers = Customer.objects.all()
    last_five_customer = Customer.objects.all().order_by('-id')[:5]

    orders = Order.objects.all()
    last_five_orders = Order.objects.all().order_by('-id')[:5]

    total_customers = customers.count()
    total_orders = orders.count()
    total_delivered = orders.filter(status='Delivered').count()
    total_pending = orders.filter(status='Pending').count()

    context = {
        'last_five_orders': last_five_orders,
        'last_five_customer': last_five_customer,
        'customers': customers,
        'orders': orders,
        'total_customers': total_customers,
        'total_orders': total_orders,
        'total_delivered': total_delivered,
        'total_pending': total_pending,

    }
    return render(request, 'accounts/dashboard.html', context)

@login_required(login_url='accounts:loginPage')
@allowed_users(allowed_roles=['admin'])
def all_orders(request):
    customers = Customer.objects.all()

    orders = Order.objects.all()

    total_customers = customers.count()
    total_orders = orders.count()
    total_delivered = orders.filter(status='Delivered').count()
    total_pending = orders.filter(status='Pending').count()

    context = {
        'customers': customers,
        'orders': orders,
        'total_customers': total_customers,
        'total_orders': total_orders,
        'total_delivered': total_delivered,
        'total_pending': total_pending,

    }
    return render(request, 'accounts/all_orders.html', context)


@login_required(login_url='accounts:loginPage')
@allowed_users(allowed_roles=['admin'])
def products(request):
    products = Product.objects.all()
    context = {
        'products': products
    }
    return render(request, 'accounts/products.html', context)


@login_required(login_url='accounts:loginPage')
@allowed_users(allowed_roles=['admin'])
def customer(request, pk):
    customer = Customer.objects.get(pk=pk)
    orders = customer.order_set.all()
    order_count = orders.count()

    myFilter = OrderFilter(request.GET, queryset=orders)
    orders = myFilter.qs
    context = {
        'customer': customer,
        'orders': orders,
        'order_count': order_count,
        'myFilter': myFilter,
    }
    return render(request, 'accounts/customer.html', context)


@login_required(login_url='accounts:loginPage')
@allowed_users(allowed_roles=['admin'])
def create_order(request, pk):
    OrderFormSet = inlineformset_factory(Customer, Order, fields=('product', 'status'), extra=10)
    customer = Customer.objects.get(pk=pk)
    formset = OrderFormSet(queryset=Order.objects.none(), instance=customer)
    # form = CreateOrderForm(initial={'customer': customer})
    if request.method == 'POST':
        formset = OrderFormSet(request.POST, instance=customer)
        if formset.is_valid():
            formset.save()
            return redirect('accounts:dashboard')

    context = {
        'formset': formset
    }

    return render(request, 'accounts/create_order.html', context)


@login_required(login_url='accounts:loginPage')
@allowed_users(allowed_roles=['admin'])
def update_order(request, pk):
    order = Order.objects.get(pk=pk)
    form = CreateOrderForm(instance=order)
    if request.method == 'POST':
        form = CreateOrderForm(request.POST, instance=order)
        if form.is_valid():
            form.save()
            messages.success(request, f'{order} has been updated.')
            return redirect('accounts:dashboard')

    context = {
        'form': form
    }

    return render(request, 'accounts/update_order.html', context)


@login_required(login_url='accounts:loginPage')
@allowed_users(allowed_roles=['admin'])
def delete_order(request, pk):
    order = Order.objects.get(pk=pk)
    if request.method == 'POST':
        order.delete()
        messages.success(request, f'{order} has been deleted.')
        return redirect('accounts:dashboard')

    context = {
        'order': order
    }

    return render(request, 'accounts/delete_order.html', context)


@unauthenticated_user
def register(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Accounts has been successfully created for {username} ')
            return redirect('accounts:loginPage')

    context = {
        'form': form,
    }
    return render(request, 'accounts/register.html', context)

@unauthenticated_user
def loginPage(request):
    if request.user.is_authenticated:
        return redirect('accounts:dashboard')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password =request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('accounts:dashboard')
            else:
                messages.info(request, 'Username OR password is incorrect')

        context = {}
        return render(request, 'accounts/login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('accounts:loginPage')


@login_required(login_url='accounts:loginPage')
@allowed_users(allowed_roles=['customer'])
def userPage(request):
    orders = request.user.customer.order_set.all()

    total_orders = orders.count()
    total_delivered = orders.filter(status='Delivered').count()
    total_pending = orders.filter(status='Pending').count()

    context = {
        'orders': orders,
        'total_orders': total_orders,
        'total_delivered': total_delivered,
        'total_pending': total_pending,
        'orders': orders,

    }
    return render(request, 'accounts/user.html', context)

# Customer Profile
@login_required(login_url='accounts:loginPage')
@allowed_users(allowed_roles=['customer'])
def accountSettings(request):
    customer = request.user.customer
    form = CustomerForm(instance=customer)

    if request.method == 'POST':
        form = CustomerForm(request.POST, request.FILES, instance=customer)
        if form.is_valid():
            form.save()
            messages.success(request, f'Accounts has been updated')

    context = {
        'form': form
    }

    return render(request, 'accounts/account_settings.html', context)




from accounts.forms import ModelPurchaseForm
from django.forms.formsets import formset_factory
def create_purchase(request):
    formset = formset_factory(ModelPurchaseForm, extra=3)

    if request.method == 'POST':
        formset = formset(request.POST)
        if formset.is_valid():
            print('form is valid')
        else:
            if formset.errors:
                print(formset.errors)
    context = {
        'formset': formset,
    }

    return render(request, 'accounts/formset.html', context)

accounts/templates/accounts/all_orders.html
{% extends 'accounts/base.html' %}
{% block content %}
<br>

<div class="row">
    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white  mb-3" id="total-orders">
                <div class="card-header">
                    <h5 class="card-title">Total Orders</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ total_orders }}</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white  mb-3" id="orders-delivered">
                <div class="card-header">
                    <h5 class="card-title">Orders Delivered</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ total_delivered }}</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white  mb-3" id="orders-pending">
                <div class="card-header">
                    <h5 class="card-title">Orders Pending</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ total_pending }}</h3>
                </div>
            </div>
        </div>
    </div>
</div>



<br>

<div class="row">
    <div class="col-md">
        <div class="card card-body">
                <table class="table table-gray table-sm table-borderless">
                  <thead>
                    <tr>
                        <th></th>
                        <th scope="col">Product</th>
                        <th scope="col">Note</th>
                        <th scope="col">Date Orderd</th>
                        <th scope="col">Status</th>
                        <th scope="col">Update</th>
                        <th scope="col">Remove</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for order in orders %}
                        <tr>
                            <td><input type="checkbox"  name="instance" value="{{obj.id}}"></td>
                            <td scope="row">{{ order.product }}</td>
                            <td scope="row">{{ order.note }}</td>
                            <td scope="row">{{ order.date_created }}</td>
                            <td scope="row">{{ order.status }}</td>
                            <td scope="row"><a class="btn btn-sm btn-primary" href="{% url 'accounts:update_order' order.pk %}">Update</a></td>
                            <td scope="row"><a class="btn btn-sm btn-danger" href="{% url 'accounts:delete_order' order.pk %}">Remove</a></td>
                        </tr>
                    {% endfor %}
                  </tbody>
                </table>
        </div>
    </div>
</div>



{% endblock content %}

<!-- <td><input type="checkbox"  name="instance" value="{{obj.id}}"></td> -->

accounts/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'inventory/style.css' %}"> -->
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
    <style>
    #logo{
        }

        body{
            background-color: #ebeff5;
        }


        #total-orders{
            background-color: #4cb4c7;
        }


        #orders-delivered{
            background-color: #7abecc;
        }

        #orders-pending{
            background-color: #7CD1C0;
        }
    </style>
    <!-- Font Icon -->

    <title>Accounts</title>

    <style>


  </style>
<!--  -->
</head>
<body>
  <header class="site-header">
    {%  include 'accounts/navbar.html' %}
  </header>



  {% block content %}

  {% endblock %}




    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<!--     <script src="vendor/jquery/jquery.min.js"></script>
    <script src="js/main.js"></script>
</body> -->
</html>

accounts/templates/accounts/dashboard.html
{%  extends 'accounts/base.html' %}

{% block content %}

{%  include 'accounts/status.html' %}

    <br>

    <div class="row card-pd">
        <div class="col-md-5">
            <h5>CUSTOMERS:</h5>
            <hr>
            <div class="card card-body">
                <!-- <a class="btn btn-primary  btn-sm btn-block" href="">Create Customer</a> -->
                <table class="table table-sm table-borderless">
                    <tr>
                        <th>Customer</th>
                        <th>Phone</th>
                        <th>Action</th>
                    </tr>
                     {% for customer in last_five_customer %}
                        <tr>
                            <td>{{ customer.name }}</td>
                            <td>{{ customer.phone }}</td>
                            <td><a href="{% url 'accounts:customer' customer.pk %}">View</a></td>

                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>

        <div class="col-md-7">
            <h5>LAST 5 ORDERS</h5>
            <hr>
            <div class="card card-body">
            {% for message in messages %}
                <p class="alert alert-{{ message.tags }}">{{message}}</p>
            {% endfor %}
                <table class="table table-sm table-borderless">
                    <tr>
                        <th>Product</th>
                        <th>Date Orderd</th>
                        <th>Status</th>
                        <th>Update</th>
                        <th>Remove</th>
                    </tr>
                    {% for order in last_five_orders %}
                        <tr>
                            <td>{{ order.product }}</td>
                            <td>{{ order.date_created }}</td>
                            <td>{{ order.status }}</td>
                            <td><a class="btn btn-sm btn-info" href="{% url 'accounts:update_order' order.pk %}">Update</a></td>
                            <td><a class="btn btn-sm btn-danger" onclick="return confirm('Are you sure you want to delete {{ order }}?');" >Remove</a></td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>

    </div>

{% endblock %}

accounts/templates/accounts/delete_order.html
{% extends 'accounts/base.html' %}
{% block content %}
<div class="card card-body text-center">

    <p>Are you sure you want to delete {{ order }}? </p>

    <form action="{% url 'accounts:delete_order' order.pk %}" method="POST">
        {% csrf_token %}
        <a class="btn btn-sm btn-info" href="{% url 'accounts:dashboard' %}">Cancel</a>
        <input class="btn btn-sm btn-danger" onclick="return confirm('Are you sure?');" type="submit" name="Confirm">
<!--         <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure?');"> -->
    </form>

</div>
{% endblock %}

<!-- <div class="row card-pd">
        <div class="col-md-5">
            <div class="card card-body">

         </div>
     </div>
</div>
 -->

accounts/templates/accounts/formset.html
{% extends 'accounts/base.html' %}
{% block content %}

<form action="" method="POST">
    {% csrf_token %}
{{ formset.management_form }}
{% for form in formset %}
    {{ form.as_p }} <hr>
{% endfor %}

<button type="submit">submit</button>
</form>


{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% block content %}
<!DOCTYPE html>
<html>

<head>
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


    <style>
        body,
        html {
            margin: 0;
            padding: 0;
            height: 100%;
            background: #E0FFFF !important;
        }
        .user_card {
            width: 350px;
            margin-top: auto;
            margin-bottom: auto;
            background: #74cfbf;
            position: relative;
            display: flex;
            justify-content: center;
            flex-direction: column;
            padding: 10px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            border-radius: 5px;

        }

        .form_container {
            margin-top: 20px;
        }

        #form-title{
            color: #fff;

        }

        .login_btn {
            width: 100%;
            background: #33ccff !important;
            color: white !important;
        }
        .login_btn:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }
        .login_container {
            padding: 0 2rem;
        }
        .input-group-text {
            background: #f7ba5b !important;
            color: white !important;
            border: 0 !important;
            border-radius: 0.25rem 0 0 0.25rem !important;
        }
        .input_user,
        .input_pass:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        #messages{
            background-color: grey;
            color: #fff;
            padding: 10px;
            margin-top: 10px;
        }
    </style>

</head>
<body>
    <div class="container h-100">
        <div class="d-flex justify-content-center h-100">
            <div class="user_card">
                <div class="d-flex justify-content-center">


                    <h3 id="form-title">LOGIN</h3>
                </div>
                <div class="d-flex justify-content-center form_container">
                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            <input type="text" name="username" placeholder="Username..." class="form-control">
                        </div>
                        <div class="input-group mb-2">
                            <div class="input-group-append">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                                <input type="password" name="password" placeholder="Password..." class="form-control" >
                        </div>

                            <div class="d-flex justify-content-center mt-3 login_container">
                                <input class="btn login_btn" type="submit" value="Login">
                            </div>
                    </form>

                </div>
                {% for message in messages %}
                    <p id="message">{{message}}</p>
                {% endfor %}
                <div class="mt-4">
                    <div class="d-flex justify-content-center links">
                        Don't have an account? <a href="{% url 'accounts:register' %}" class="ml-2">Sign Up</a>
                    </div>
                    <div class="d-flex justify-content-center links">
                        Forget password? <a href="{% url 'password_reset' %}" class="ml-2">Reset Password</a>
                    </div>

                </div>
            </div>
        </div>
    </div>
</body>

</html>

{% endblock content %}

accounts/templates/accounts/navbar.html
{% load static %}

<style>
  .hello-msg{
    font-size: 18px;
    color: #fff;
    margin-right: 20px;
  }
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  {% if request.user.customer %}
  <a class="navbar-brand" href="{% url 'accounts:userPage' %}">Hasina Construction</a>
  {% else %}
  <a class="navbar-brand" href="{% url 'accounts:dashboard' %}">Hasina Construction</a>
  {% endif %}
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          {% if request.user.is_staff %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'accounts:dashboard' %}">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:products' %}">Products</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:all_orders' %}">Orders</a>
          </li>
          {% endif %}
          {% if request.user.customer %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:accountSettings' %}">Settings</a>
          </li>
          {% endif %}
        </ul>
      </div>
  {% if request.user.customer or request.user.is_staff %}
  <span class="hello-msg">Hello, {{request.user}}</span>
  <span ><a  class="hello-msg" href="{% url 'accounts:logoutUser' %}">Logout</a></span>
  {% endif %}

</nav>

accounts/templates/accounts/password_reset.html
{% extends 'accounts/base.html' %}
{% block content %}
<div class="card card-body text-center">


<h3>Password reset</h3>

<p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>

<form method="post">

    {% csrf_token %}
    {{form.as_p}}
    <input type="Submit" name="Send email">

</form>


</div>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'accounts/base.html' %}
{% block content %}
<div class="card card-body text-center">

    <h3>Password reset complete</h3>

    <p>Your password has been set. You may go ahead and log in now.</p>

    <a href="{% url 'accounts:dashboard' %}">Log in</a>


</div>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'accounts/base.html' %}
{% block content %}
<div class="card card-body text-center">


    <h3>Password reset sent</h3>


    <p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>

    <p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>


</div>
{% endblock %}

accounts/templates/accounts/products.html
{% extends 'accounts/base.html' %}
{% block content %}

        <br>

        <div class="row">
            <div class="col-md">
                <div class="card card-body">
                    <h5>Products</h5>
                </div>
                <div class="card card-body">
                    <table class="table table-borderless">
                        <tr>
                            <th>Product</th>
                            <th>Category</th>
                            <th>Price</th>
                        </tr>
                        {% for product in products %}
                            <tr>
                                <td>{{ product.name }}</td>
                                <td>{{ product.category }}</td>
                                <td>{{ product.price }} BDT</td>
                            </tr>
                        {% endfor %}

                    </table>
                </div>
            </div>

        </div>

{% endblock content %}

accounts/templates/accounts/status.html
<br>

<div class="row">
    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white  mb-3" id="total-orders">
                <div class="card-header">
                    <h5 class="card-title">Total Orders</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ total_orders }}</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white  mb-3" id="orders-delivered">
                <div class="card-header">
                    <h5 class="card-title">Orders Delivered</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ total_delivered }}</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white  mb-3" id="orders-pending">
                <div class="card-header">
                    <h5 class="card-title">Orders Pending</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{ total_pending }}</h3>
                </div>
            </div>
        </div>
    </div>
</div>